---
spec:
- name: build
  tasks:
  - name: build
    # `run` task arguments are the only things that can be
    # overridden from a pipeline. This is to guarantee that
    # what the user does is what the pipeline does.
    arguments:
      GOOS:
        value: linux
